---
abstract: 'Access DuckDuckGo search results via variables'
author:
  - 'Curtis Brandt <curtis@cpan.org>'
build_requires:
  Test::More: '0.96'
  Test::RequiresInternet: '0.02'
configure_requires:
  Module::Build::Tiny: '0.036'
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.5, Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Tie-DuckDuckGo
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  Carp: '0.0'
  HTML::TreeBuilder::XPath: '0.0'
  HTTP::Tiny: '0.0'
  URI: '0.0'
  perl: '5.008005'
resources:
  bugtracker: https://github.com/aggrolite/Tie-DuckDuckGo/issues
  homepage: https://github.com/aggrolite/Tie-DuckDuckGo
  repository: https://github.com/aggrolite/Tie-DuckDuckGo.git
version: '0.02'
